#!/bin/bash
PATH=./node_modules/.bin:$PATH

function install {
    npm install
}

function generate_api {
    dotenv -e .env -- sh -c 'npx swagger-typescript-api -p $NEXT_PUBLIC_API_URL/api-json -o ./api -n document.ts'
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
